get_logs_max_results = 10000
retain-blocks = -1
retain_interval_blocks = 100
use_litedb = false
blocks_kept_ads = 10000
blocks_kept_db = -1
sig_cache_size = 20000
trunk_cache_size = 200
prune_every_n = 10
recheck_threshold = 1000
mainnet-rpc-url = "http://127.0.0.1:57319"
mainnet-genesis-height = 121900
mainnet-rpc-username = "zeniq"
mainnet-rpc-password = "zeniq123"
zeniqsmart-rpc-url = "https://smart.zeniq.network:9545"

blocks-behind = 0
update-of-ads-log = false
height-revision = [ [0, 7], [66123456, 11] ]

# the following 2 consensus-relevant
cc-rpc-epochs=[[220200,100,100000]]
cc-rpc-fork-block=16880000



