# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# eth_getLogs max return items
get_logs_max_results = 10000

# retain blocks in TM
retain-blocks = -1

# every retain_interval_blocks blocks execute TM blocks prune
retain_interval_blocks = 100

# use liteDB
use_litedb = false
with-syncdb = false

# How many recent blocks can be kept in ads (to prune the blocks which are older than them)
blocks_kept_ads = 10000

# How many recent blocks can be kept in db (to prune the blocks which are older than them)
blocks_kept_db = -1

# The entry count limit of the signature cache, which caches the recent signatures' check results
sig_cache_size = 20000

# The initial entry count in the trunk cache, which buffers the write operations of the last block
trunk_cache_size = 200

# We try to prune the old blocks of ads every n blocks
prune_every_n = 10

# If the number of the mempool transactions which need recheck is larger than this threshold, stop
# adding new transactions into mempool
recheck_threshold = 1000

# BCH mainnet rpc url
mainnet-rpc-url = "http://127.0.0.1:57319"

mainnet-genesis-height = 121900

# BCH mainnet rpc username
mainnet-rpc-username = "zeniq"

# BCH mainnet rpc password
mainnet-rpc-password = "zeniq123"

watcher-speedup = true
zeniqsmart-rpc-url = "https://smart3.zeniq.network:9545"

blocks-behind = 0
update-of-ads-log = false

# CCRPCForkBlock: close to MaxInt64, eg 9123456789123456789, to disable
# this is an example only
cc-rpc-fork-block = 55555555

# CCRPCEpochs: consensus-relevant
# [[mainnetHeight>=184464,e>=6,>=e*2*10*60/3],...]
# this is an example only
cc-rpc-epochs = [[302400,1008,403200]]

# HeightRevision consensus-relevant
# 7=EVMC_ISTANBUL  is default from 0, 11=EVMC_SHANGHAI, next block > 14444444
# this is an example only
height-revision = [ [0, 7], [55555555, 11] ]

